# Generated by Django 3.2.3 on 2023-08-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursosLeccionesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(upload_to='datos')),
                ('description', models.TextField(blank=True)),
                ('alt', models.TextField(blank=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.course')),
            ],
        ),
    ]
