# Generated by Django 3.2.3 on 2024-02-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0003_alter_grupo_course'),
        ('defapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='leccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson'),
        ),
    ]
