# Generated by Django 3.2.3 on 2024-02-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defapp', '0002_datos_leccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='datos'),
        ),
    ]
