# Generated by Django 3.2.3 on 2024-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defapp', '0004_remove_datos_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
