# Generated by Django 3.2.3 on 2023-08-05 20:53

import ckeditor.fields
import cursosLeccionesapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('miniatura', models.ImageField(upload_to='imgcouses')),
                ('anio', models.CharField(max_length=120)),
                ('alt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('privado', models.BooleanField(default=False)),
                ('imagen_grupo', models.ImageField(blank=True, upload_to='images_groups')),
                ('codigo_unico', models.CharField(blank=True, default=cursosLeccionesapp.models.generate_random_code, max_length=8, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.course')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='lesson')),
                ('video_e', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('ejercicio', models.CharField(blank=True, max_length=100)),
                ('alt', models.TextField(blank=True)),
                ('contentenido', ckeditor.fields.RichTextField(blank=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of the quiz in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='required score in %')),
                ('difficluty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
                ('fk_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.grupo')),
                ('lessson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('fk_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.grupo')),
                ('fk_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TaskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.estudiante')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='parrafoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nposition', models.IntegerField()),
                ('contenido', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='LessonImages')),
                ('alt', models.TextField(blank=True)),
                ('leccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.grupo')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.result')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('lessson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('n_orden', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.question')),
            ],
        ),
    ]
