# Generated by Django 3.2.3 on 2023-09-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mostrar',
            field=models.BooleanField(default=False, verbose_name='mostrar leccion'),
        ),
    ]
