# Generated by Django 3.2.3 on 2024-02-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0003_alter_grupo_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
