# Generated by Django 3.2.3 on 2023-10-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0002_lesson_mostrar'),
        ('juegosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('leccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='cardpar',
            name='lesson_cards',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartas_de_leccion', to='juegosapp.lesson_cards'),
        ),
    ]
