# Generated by Django 3.2.3 on 2023-10-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0002_lesson_mostrar'),
        ('juegosapp', '0003_auto_20231016_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_cards',
            name='grupofk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.grupo'),
        ),
        migrations.AlterField(
            model_name='lesson_cards',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson'),
        ),
        migrations.AlterField(
            model_name='listquiz',
            name='grupofk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.grupo'),
        ),
        migrations.AlterField(
            model_name='listquiz',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson'),
        ),
    ]
