# Generated by Django 3.2.3 on 2023-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesUnityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_juegos_lesson',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
