# Generated by Django 3.2.3 on 2023-09-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesUnityapp', '0002_alter_score_juegos_lesson_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score_juegos_lesson',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
