# Generated by Django 3.2.3 on 2023-09-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
        ('gamesUnityapp', '0003_alter_score_juegos_lesson_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntos_obtenidos', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.estudiante')),
            ],
        ),
    ]
