# Generated by Django 3.2.3 on 2023-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesUnityapp', '0004_historialexperiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialexperiencia',
            name='puntos_obtenidos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
