# Generated by Django 3.2.3 on 2023-10-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
        ('cursosLeccionesapp', '0002_lesson_mostrar'),
        ('gamesUnityapp', '0005_alter_historialexperiencia_puntos_obtenidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_juegos_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.estudiante')),
                ('juego_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursosLeccionesapp.grupo')),
            ],
        ),
    ]
