# Generated by Django 3.2.3 on 2024-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesUnityapp', '0006_score_juegos_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='score_juegos_lesson',
            name='score_perfecto',
            field=models.BooleanField(default=False),
        ),
    ]
