# Generated by Django 3.2.3 on 2024-02-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_estudiante_total_score_perfect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='total_score_perfect',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
