# Generated by Django 3.2.3 on 2023-10-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0002_lesson_mostrar'),
        ('ciertoFalsoapp', '0002_pregunta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_True_false',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('leccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='test_TF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciertoFalsoapp.test_true_false'),
        ),
    ]
