# Generated by Django 3.2.3 on 2023-10-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciertoFalsoapp', '0003_auto_20231004_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='test_TF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_test_tf', to='ciertoFalsoapp.test_true_false'),
        ),
    ]
