# Generated by Django 3.2.3 on 2023-10-17 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursosLeccionesapp', '0002_lesson_mostrar'),
        ('ciertoFalsoapp', '0005_test_true_false_grupofk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_true_false',
            name='grupofk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.grupo'),
        ),
        migrations.AlterField(
            model_name='test_true_false',
            name='leccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursosLeccionesapp.lesson'),
        ),
    ]
